exports.destinations = [
    { name: 'Kuwait', fruit: 'Date', fruitImage: "../img/fruits/dates.jpg", attraction: 'Kubbar Island', attractionImage: '../img/attractions/kubbarIsland.jpg' , destinationImage: '../img/destinations/kuwait.jpg' , seSalary: 33116, cardDescription: 'Kuwait, country of the Arabian Peninsula located in the northwestern corner of the Persian Gulf. A small emirate nestled between Iraq and Saudi Arabia, Kuwait is situated in a section of one of the driest, least-hospitable deserts on Earth. Its shore, however, includes Kuwait Bay, a deep harbour on the Persian Gulf.' },
    { name: 'Nicaragua', fruit: 'Papaya', fruitImage: "../img/fruits/papaya.jpg", attraction: 'Islets of Granada', attractionImage: '../img/attractions/isletsOfGranada.jpg', destinationImage: '../img/destinations/nicaragua.jpg', seSalary: 5698, cardDescription: 'Nicaragua is the largest country in Central America and is slightly bigger in area than New York State. The country is bordered by Honduras to the north and Costa Rica to the south. The Pacific Ocean provides the border to the west, and the eastern border of the country is on the Caribbean Sea.' },
    { name: 'Canary Islands', fruit: 'Banana', fruitImage: "../img/fruits/banana.jpg", attraction: 'Tenerife for dolphin and whale watching', attractionImage: '../img/attractions/tenerifeWhale.jpg', destinationImage: '../img/destinations/canary-islands.jpg' , seSalary: 26627, cardDescription: 'The Canary Islands are the southernmost region of Spain, and the largest and most populous archipelago of Macaronesia. Because of their location, the Canary Islands have historically been considered a link between the four continents of Africa, North America, South America, and Europe.' },
    { name: 'Pakistan', fruit: 'Mango', fruitImage: "../img/fruits/mango.jpg", attraction: 'Hunza Valley', attractionImage: '../img/attractions/hunzaValley.jpg', destinationImage: '../img/destinations/pakistan.jpg' , seSalary: 10919, cardDescription: 'Pakistan is a country located in South Asia. It has a coastline along the Arabia Sea and the Gulf of Oman and is bordered by Afghanistan, China, India, and Iran. The geography of Pakistan is diverse with the Thar Desert in the east and the Hindu Kush and Pamir mountain ranges in the north.' },
    { name: 'Japan', fruit: 'Persimmons', fruitImage: "../img/fruits/persimmons.jpg", attraction: 'Kyoto', attractionImage: '../img/attractions/kyoto.jpg', destinationImage: '../img/destinations/japan.jpg' , seSalary: 62898, cardDescription: "Japan is an archipelago, or string of islands, on the eastern edge of Asia. There are four main islands: Hokkaido, Honshu, Shikoku, and Kyushu. There are also nearly 4,000 smaller islands! Japan's nearest mainland neighbors are the Siberian region of Russia in the north and Korea and China farther south." },
    { name: 'India', fruit: 'Mango', fruitImage: "../img/fruits/mangoIndia.jpg", attraction: 'Jaisalmer - the Golden City', attractionImage: '../img/attractions/jaisalmer.jpg', destinationImage: '../img/destinations/india.jpg' , seSalary: 7647, cardDescription: "India, country that occupies the greater part of South Asia. Its capital is New Delhi, built in the 20th century just south of the historic hub of Old Delhi to serve as India’s administrative centre. Its government is a constitutional republic that represents a highly diverse population consisting of thousands of ethnic groups and likely hundreds of languages." },
    { name: 'Switzerland', fruit: 'Apple', fruitImage: "../img/fruits/apple.jpg", attraction: 'Jungfraujoch - the Top of the World', attractionImage: '../img/attractions/jungfraujoch.jpg', destinationImage: '../img/destinations/switzerland.jpg' , seSalary: 103089, cardDescription: "Switzerland is a small mountainous country located in central Europe. This landlocked country is about the size of New Jersey and is between France and Italy. It is also bordered by Austria, Germany, and Liechtenstein."  },
    { name: 'Portugal', fruit: 'Passion Fruit', fruitImage: "../img/fruits/passionFruit.jpg", attraction: 'Mosteiro dos Jeronimos', attractionImage: '../img/attractions/mosteiro.jpg', destinationImage: '../img/destinations/portugal.jpg' , seSalary: 26762, cardDescription: "Portugal is the westernmost point of Europe and lies on the west coast of the Iberian Peninsula. The long Atlantic coastline is popular with visitors and locals alike. Surfers are drawn to the strong surf in the west, and the warm, sandy beaches in the south are a haven for tourists." },
    { name: 'New Zealand', fruit: 'Kiwifruit', fruitImage: "../img/fruits/kiwifruit.jpg", attraction: 'Fiordland National park and Milford Sound', attractionImage: '../img/attractions/fiordland.jpg', destinationImage: '../img/destinations/new-zealand.jpg' , seSalary: 47248, cardDescription: "New Zealand (NZ) is an island country in the South Pacific Ocean located about 2,000 km (1,300 mi) southeast of Australia. The island-nation consists of some smaller islands and two main islands, the North Island (Te-Ika-a-Maui) and the South Island (Te Wai Pounamu), which are separated by the Cook Strait." },
    { name: 'Taiwan', fruit: 'Pineapple', fruitImage: "../img/fruits/pineapple.jpg", attraction: 'Night Markets', attractionImage: '../img/attractions/juifen.jpg', destinationImage: '../img/destinations/taiwan.jpg' , seSalary: 100000, cardDescription: "Taiwan is a semi-tropical island in East Asia, one of the world's most exciting and rapidly changing regions. Like many other places in Asia, Taiwan is densely populated and highly developed in terms of economics, technology and transport. Its people are highly educated and well traveled." }
]