exports.destinations = [
    { name: 'Kuwait', fruit: 'Date', fruitImage: "../img/fruits/dates.jpg", attraction: 'Kubbar Island', attractionImage: '../img/attractions/kubbarIsland.jpg' , destinationImage: '../img/destinations/kuwait.jpg' , seSalary: 33116 },
    { name: 'Nicaragua', fruit: 'Papaya', fruitImage: "../img/fruits/papaya.jpg", attraction: 'Islets of Granada', attractionImage: '../img/attractions/isletsOfGranada.jpg', destinationImage: '../img/destinations/nicaragua.jpg', seSalary: 5698 },
    { name: 'Canary Islands', fruit: 'Banana', fruitImage: "../img/fruits/banana.jpg", attraction: 'Tenerife for dolphin and whale watching', attractionImage: '../img/attractions/tenerifeWhale.jpg', destinationImage: '../img/destinations/canary-islands.jpg' , seSalary: 26627 },
    { name: 'Pakistan', fruit: 'Mango', fruitImage: "../img/fruits/mango.jpg", attraction: 'Hunza Valley', attractionImage: '../img/attractions/hunzaValley.jpg', destinationImage: '../img/destinations/pakistan.jpg' , seSalary: 10919 },
    { name: 'Japan', fruit: 'Persimmons', fruitImage: "../img/fruits/persimmons.jpg", attraction: 'Kyoto', attractionImage: '../img/attractions/kyoto.jpg', destinationImage: '../img/destinations/japan.jpg' , seSalary: 62898 },
    { name: 'India', fruit: 'Mango', fruitImage: "../img/fruits/mangoIndia.jpg", attraction: 'Jaisalmer - the Golden City', attractionImage: '../img/attractions/jaisalmer.jpg', destinationImage: '../img/destinations/india.jpg' , seSalary: 7647 },
    { name: 'Switzerland', fruit: 'Apple', fruitImage: "../img/fruits/apple.jpg", attraction: 'Jungfraujoch - the Top of the World', attractionImage: '../img/attractions/jungfraujoch.jpg', destinationImage: '../img/destinations/switzerland.jpg' , seSalary: 103089  },
    { name: 'Portugal', fruit: 'Passion Fruit', fruitImage: "../img/fruits/passionFruit.jpg", attraction: 'Mosteiro dos Jeronimos', attractionImage: '../img/attractions/mosteiro.jpg', destinationImage: '../img/destinations/portugal.jpg' , seSalary: 26762 },
    { name: 'New Zealand', fruit: 'Kiwifruit', fruitImage: "../img/fruits/kiwifruit.jpg", attraction: 'Fiordland National park and Milford Sound', attractionImage: '../img/attractions/fiordland.jpg', destinationImage: '../img/destinations/new-zealand.jpg' , seSalary: 47248 },
    { name: 'Taiwan', fruit: 'Pineapple', fruitImage: "../img/fruits/pineapple.jpg", attraction: 'Jiufen Night Market', attractionImage: '../img/attractions/juifen.jpg', destinationImage: '../img/destinations/taiwan.jpg' , seSalary: 100000 }
]